package database

import (
	"reflect"
	"strings"
	"testing"
)

// 固定の改名一覧。行の UPDATE や歌った人の関連の改名を追加しても通さない。
// 実 PostgreSQL でのデータ・参照制約の検証は別の統合テストが担当する。
func TestChannelRenameSQL(t *testing.T) {
	data, err := migrationFS.ReadFile("migrations/069_rename_channels.sql")
	if err != nil {
		t.Fatal(err)
	}
	var tokens, statements []string
	for i := 0; i < len(data); {
		token, next, err := migrationSQLToken(string(data), i)
		if err != nil {
			t.Fatal(err)
		}
		i = next
		if token == ";" {
			statements = append(statements, strings.Join(tokens, " "))
			tokens = nil
		} else if token != "" {
			tokens = append(tokens, token)
		}
	}
	if len(tokens) != 0 {
		t.Fatal("unterminated statement")
	}
	want := []string{
		"ALTER TABLE SINGERS RENAME TO CHANNELS",
		"ALTER TABLE STREAM_SINGERS RENAME TO STREAM_CHANNELS",
		"ALTER TABLE STREAM_CHANNELS RENAME COLUMN SINGER_ID TO CHANNEL_ID",
		"ALTER TABLE BATCH_FILL_RUNS RENAME COLUMN SINGER_ID TO CHANNEL_ID",
		"ALTER TABLE CHANNELS RENAME CONSTRAINT SINGERS_PKEY TO CHANNELS_PKEY",
		"ALTER TABLE CHANNELS RENAME CONSTRAINT SINGERS_ORGANIZATION_FKEY TO CHANNELS_ORGANIZATION_FKEY",
		"ALTER TABLE CHANNELS RENAME CONSTRAINT SINGERS_ORGANIZATION_OVERRIDE_FKEY TO CHANNELS_ORGANIZATION_OVERRIDE_FKEY",
		"ALTER TABLE CHANNELS RENAME CONSTRAINT SINGERS_MEMBERS_ONLY_POLICY_CHECK TO CHANNELS_MEMBERS_ONLY_POLICY_CHECK",
		"ALTER TABLE STREAM_CHANNELS RENAME CONSTRAINT STREAM_SINGERS_PKEY TO STREAM_CHANNELS_PKEY",
		"ALTER TABLE STREAM_CHANNELS RENAME CONSTRAINT STREAM_SINGERS_STREAM_ID_FKEY TO STREAM_CHANNELS_STREAM_ID_FKEY",
		"ALTER TABLE STREAM_CHANNELS RENAME CONSTRAINT STREAM_SINGERS_SINGER_ID_FKEY TO STREAM_CHANNELS_CHANNEL_ID_FKEY",
		"ALTER INDEX IDX_SINGERS_VISIBLE RENAME TO IDX_CHANNELS_VISIBLE",
		"ALTER INDEX IDX_SINGERS_AUTO_FILL RENAME TO IDX_CHANNELS_AUTO_FILL",
		"ALTER INDEX IDX_STREAM_SINGERS_STREAM_ID RENAME TO IDX_STREAM_CHANNELS_STREAM_ID",
		"ALTER INDEX IDX_STREAM_SINGERS_SINGER_ID RENAME TO IDX_STREAM_CHANNELS_CHANNEL_ID",
		"ALTER INDEX IDX_STREAM_SINGERS_OWNER RENAME TO IDX_STREAM_CHANNELS_OWNER",
		"ALTER TRIGGER UPDATE_SINGERS_UPDATED_AT ON CHANNELS RENAME TO UPDATE_CHANNELS_UPDATED_AT",
	}
	if !reflect.DeepEqual(statements, want) {
		t.Fatalf("migration statements:\n%q\nwant:\n%q", statements, want)
	}
}
